# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myuser_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='staff',
        ),
    ]
