# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('account', '0017_auto_20180530_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags1',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='taggit.Tag'),
        ),
    ]
